## Name: Uras Ayanoglu
## Number: 2203334

# Tasks for week 4

In these exercises, we are going deeper with the idea of recursion and iteration.

We will also try to bring in the idea of writing different implementations to the same problem, comparing the efficiency of the different versions. The ultimate goal is not to find every single way of implementation, it is good enough to compare at least two different ways.

The aim here is, first of all, to enhance flexible problem solving skills. The most intuitive one is the easiest to implement but probably not the most efficient one. That is why it is necessary to also try discovering other solutions to the same problem.

## Task 1 Palindrome checker

A number or a string is s palindrome, if they read the same forwards and backwards.

For example 1234321 is a number palindrome and *madam* is a string palindrome.


**Your task** is to write an algorithm *isPal(phrase)* that returns **True** if the input is a palindrome and **False** otherwise.

There are several ways to implement palindrome checker:
1) reverse the original sequence and checking whether the reversed is the same as the original, element by element
2) reverse the original and comparing, using string operations (also for numbers)
3) comparing the elements from the same place in opposite ends

Implement these in the way you find to be most optimal, both in time and space complexity.


In [1]:
def isPal(sample):
    return str(sample)[::-1] == str(sample)

print("*" * 10)
print(isPal("masd"))
print(isPal(1234321))
print(isPal("step on no pets"))

def isPal_iter(sample):
    left_to_right = []
    right_to_left = []
    for item in str(sample):
        left_to_right.append(item)
    for item in str(sample)[::-1]:
        right_to_left.append(item)
    for i in range(len(str(sample))):
        if left_to_right[i] != right_to_left[i]:
            return False
        else:
            return True
print("*" * 10)
print(isPal_iter("masd"))       
print(isPal_iter(1234321))
print(isPal_iter("Step on no pets"))

def isPal_3rd(sample):
    for i in range(len(str(sample))):
        return str(sample)[i] == (str(sample)[::-1])[i]
    
def isPal_4th(sample):
    end = len(sample) - 1
    
    for i in range(len(sample)//2):
        if sample[i] != sample[end - i]:
            return False
        return True
    
print(isPal_4th("step on no pets"))

print("*" * 10)
print(isPal_3rd("masd"))
print(isPal_3rd(1234321))
print(isPal("Step on no pets"))

print("\nRuntime comparisons of the functions:")
"""
print("\nisPal function:")
%timeit isPal("step on no pets")
print("\nisPal_iter function:")
%timeit isPal_iter("step on no pets")
print("\nisPal_3rd function")
%timeit isPal_3rd("step on no pets")
print("\nisPal_4th function:")
%timeit isPal_4th("step on no pets")"""
# %timeit functions are commented out to prevent out of memory issues.

**********
False
True
True
**********
False
True
False
True
**********
False
True
False

Runtime comparisons of the functions:

isPal function:
251 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_iter function:
1.55 µs ± 64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_3rd function
595 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_4th function:
481 ns ± 6.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Runtime comparisons of the functions:

isPal function:
251 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_iter function:
1.55 µs ± 64 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_3rd function
595 ns ± 17.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

isPal_4th function:
481 ns ± 6.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

## Task 2 Array checker

Two arrays are considered to be the same, 
1) if the arrays are of the same length, and
2) if same elements occur in both arrays equally frequently. 

The order of items in the arrays may though vary. For example, the array $[1,2,3,3,4,5,5,5,6]$ is equal to the array $[6,3,2,5,3,1,5,4,5]$, since there is one of 1's, 2's, 4's and 6's in both arrays, two 3's and three 5's. However, arrays $[1,2,3]$ and $[1,2,2]$ are not the same, since the length of both arrays is the same 3, but the last element of the arrays differ.

Thus, the algorithm **check(A,B)** should work as follows.

### Example 1:
**INPUT:**

A = [1,2,3,3,4,5,5,5,6]

B = [6,3,2,5,3,1,5,4,5]

**OUTPUT: ** *True* or *1*

**EXPLANATION: ** *All elements occur equally frequently, but are just ordered differently*

### Example 2:
**INPUT:**

A = [1,2,3]

B = [1,2,2]

**OUTPUT: ** *False* or *0*

**EXPLANATION: ** *The last elements are not equal, other elements are.*

<span style="color:red"> **Your Task:** Complete check() function which takes both the given array and their size as function arguments and returns true if the arrays are equal else returns false.
</span>



In [2]:
def ListEquals(A,B):
    A.sort()
    return A.sort() == B.sort() # This function may return false Trues

def ListEquals_1(A,B):
    return sorted(A) == sorted(B)

A = [1,2,3,3,4,5,5,5,6]

B = [6,3,2,5,3,1,5,4,]

print(ListEquals_1(A,B))
    

False


In [18]:
def check_with_sets(a,b):
    if len(a) == len(b):
        return set(a) == set(b)
    else:
        return False

A = ["a", "b", "c", "e", "e"]
B = ["b", "c", "a", "e"]
print(check_with_sets(A,B))

C = ["a", "a", "b", "c", "d", "e", "f"]
D = ["a", "b", "c", "d", "e", "f", "f"]
print(check_with_sets(C,D)) 
# Fallback of this algorithm, list C and D have the same size, but list C has two a's whereas list D has 2 f's. It return true whereas it should have returned False!

False
True


In [27]:
A = ["a", "b", "c", "e"]
B = ["b", "c", "d", "e"]
C = "Hello Neighbor!"
D = "Hello Neighbour!"
E = (1,2,3,4,5,6,7,8,9)
F = (9,8,7,6,5,4,3,2,1)
H = {0, 2, 4, 6, 8, 8, 10} # When a set variable creation, by its nature, repeated elements will be removed automatically 
I = {0, 2, 4, 6, 8, 10}

def check_array(a,b):
    if len(a) ==  len(b):
        for item in a:
            if item not in b:
                return False
        dict_a = {}
        dict_b = {}
        for item in a:
            dict_a[item] = dict_a.get(item, 0) + 1
        for item in b:
            dict_b[item] = dict_b.get(item, 0) + 1
        res = all((dict_a.get(k) == v for k, v in dict_b.items()))
        return res
    else:
        return False
    
print(check_array(A,B))
print(check_array(C,D))
print(check_array(E,F))
print(check_array(H,I))

%timeit check_array(A,B)

False
False
True
True
335 ns ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
array1 = ["a", "b", "c", "e", "e"]
array2 = ["b", "c", "a", "e"]


def check_array3rd(A,B):
    dict_A = {}
    dict_B = {}
    
    for i in range(len(A)):
        dict_A[A[i]] = A.count(A[i])
    
    for i in range(len(B)):
        dict_B[B[i]] = B.count(B[i])
    
    return dict_A == dict_B
    

print(check_array3rd(array1,array2))


False


## Task 3: Copying a string

This algorithm takes two strings as input. The algorithm copies the first string to the other, as in the following examples:

**INPUT:**

s1 = "hello"

s2 = "world"

**OUTPUT: **

s1 = "hello"

s2 = "hello"

or

**INPUT: **

s1 = "chuck norris"

s2 = " "

**OUTPUT: **

s1 = "chuck norris"

s2 = "chuck norris"

### Your task

Implement the copying algorithm in different ways using iteration and recursion. You can also try to find other ways of copying a string **without harming the original string**. Compare the algorithms in terms of running time.


In [11]:
s1 = "Chuck Norris"
s2 = ""

def copy_string(s1, s2):
    s3 = ""
    for letter in s1:
        s3 += letter
    return s1, s3

print(s1, s2)
print(copy_string(s1, s2))


# if len(str1) <= 1:
#    return str1
#else:
# return f(str]1:) + str10

def copy_string_recursive(s1, s2):
    if len(s1) == 0 or len(s1) == 1:
        return s1[0]
    else:
        s2 = s1[0] + copy_string_recursive(s1[1:],s2)
    return s2

print(s1,s2)
print(copy_string_recursive(s1,s2))


    

Chuck Norris 
('Chuck Norris', 'Chuck Norris')
Chuck Norris 
uras


## Task 4: kth smallest element

Suppose that you are given an integer array of size $n$. The algorithm takes the array as input, natural number $k<n$ as another input, and returns the kth smallest element in the list and the index of the first occurrence of this item.

As an example, consider array A = [3,6,4,7,2,4,6,8]. If k=3, you are supposed to find the third smallest element in the array. The output of the algorithm with input A and 3 should be (4, 2), since 2 is the smallest element in the array, the second smallest is 3 with index 0, and the third smallest is 4 at index position 2.

Implement this algorithm in different ways (recirsive) and compare different implementation runtimes.

In [14]:
def nth_smallest_element(array, n):
    m = sorted(set(array)) 
    
    if n > len(m):
        print("Invalid indexing.")
    else:
        result = m[n-1]
        position_in_array = array.index(result)
    
    return (result, position_in_array)

A = [3,6,4,7,2,4,6,8]
B = "interdisciplinary"
print(nth_smallest_element(A,4))
print(nth_smallest_element(B,3))

(6, 1)
('d', 5)


## Task 5: Longest common prefix

Consider having a set of strings. Your task is to find the longest common prefix in the set of these strings, i.e. a substring which is at the beginning of each string and is the longest common such substring.

### Example

Let the set of strings consist of words *autokauppa*, *autonkuljettaja*, *auttaja* ja *aurinko*.
The algorithm takes these four strings as input.

The two first strings share **auto** as a common prefix: **auto**kauppa, **auto**nkuljettaja.

However, *auttaja* does not begin with **auto**, but has **aut** in the beginning. Thus, the longest common prefix of these three words would be **aut**.

The fourth word does not have **aut** as its prefix. However, **au** is a common prefix of all four words.

Thus, the output for the words *autokauppa*, *autonkuljettaja*, *auttaja* and *aurinko* is **au**.

### Your task

Implement the algorithm lcp(strings) taking an array of strings as input. The algorithm returns the longest common prefix of the strings in the array. Consider different implementations of the same algorithm (recursive and iterative, char by char matching,...) and compare their runtimes.

In [21]:
def longest_common_prefix(strs):
    if len(strs) == 0:
        return ""
    current = strs[0]
    for i in range(1,len(strs)):
        temp = ""
        if len(current) == 0:
            break
        for j in range(len(strs[i])):
            if j<len(current) and current[j] == strs[i][j]:
                temp+=current[j]
            else:
                break
        current = temp
    return current

input_list = ["school","schedule","scotland"]

print(longest_common_prefix(input_list))

sc
